name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_packages
      run: "sudo apt-get update; sudo apt-get -y install cppcheck-gui cppcheck clang valgrind"
    - name: cppcheck
      run: "cd sort_tester/app; make cppcheck"
    - name: make
      run: "cd sort_tester/app; make"
    - name: cov
      run: "cd sort_tester/app; make cov"
    - name: valgrind
      run: "cd sort_tester/app; make valgrind"
    - name: sanitizer
      run: "cd sort_tester/app; make sanitizer"
